- name: Get Cuda PIN file from Nvidia
  shell: "wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin"

- name: Move file to location
  shell: "mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600"

- name: Get Cuda Package
  shell: "wget http://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda-repo-ubuntu1804-10-2-local-10.2.89-440.33.01_1.0-1_amd64.deb"

- name: Dpkg Cuda package
  shell: "dpkg -i cuda-repo-ubuntu1804-10-2-local-10.2.89-440.33.01_1.0-1_amd64.deb"

- name: Add key to apt repositories
  shell: "apt-key add /var/cuda-repo-10-2-local-10.2.89-440.33.01/7fa2af80.pub"

- name: Install Cuda
  apt: pkg=cuda state=present update_cache=true
